// Replace previous import and flat types with recursive categories and richer product fields

export type MenuCategory = {
  id: string;
  name: string;
  parentId?: string;
  children: MenuCategory[];
};

export type MenuProduct = {
  id: string;
  name: string;
  description: string;
  price: number | null;
  image: string; // public path
  badge?: 'new' | 'popular' | 'recommended';
  categoryId: string; // points to a leaf or non-leaf category
  portionSizes: Array<'half' | 'full' | 'small' | 'medium' | 'large'>;
  varieties: Array<'lamb' | 'chicken' | 'veg' | 'non-veg' | 'prawn' | 'king_prawn' | 'fish' | 'beef' | 'paneer' | 'mixed_veg' | 'seafood' | 'sweet' | 'meat' | 'spicy' | 'kids' | 'mild'>;
  tags?: string[];
};

// Recursive categories tree (updated to match provided menu)
export const categories: MenuCategory[] = [
  {
    id: 'starters',
    name: 'Starters',
    children: [],
  },
  {
    id: 'starters-nonveg',
    name: 'Starters-Nonveg',
    children: [],
  },
  {
    id: 'chefs-recommend',
    name: "Chef's Recommendations",
    children: [],
  },
  {
    id: 'specialities',
    name: 'Specialities',
    children: [],
  },
  {
    id: 'traditional-curry',
    name: 'Traditional Curry Dishes',
    children: [],
  },
  {
    id: 'seafood',
    name: 'Seafood',
    children: [],
  },
  {
    id: 'from-the-clay-oven',
    name: 'From The Clay Oven - (Medium Hot)',
    children: [],
  },
  {
    id: 'malabar-biriyani',
    name: 'Malabar Biriyani',
    children: [],
  },
  {
    id: 'vegetarian',
    name: 'Vegetarian',
    children: [],
  },
  {
    id: 'rice',
    name: 'Rice',
    children: [],
  }, 
  {
    id: 'bread',
    name: 'Bread',
    children: [],
  },
  {
    id: 'extras',
    name: 'Extras',
    children: [],
  },
  {
    id: 'kids-meal',
    name: 'Kids Meal',
    children: [],
  },
];

// Products updated to reflect the menu and mapped to categories
export const products: MenuProduct[] = [
  // Starters (Veg)
  {
    id: 'pappodoms',
    name: 'Pappodoms',
    description: 'Classic Indian lentil wafers',
    price: 0.95,
    image: '/images/food/menu/starters-veg/papadom.jpg',
    badge: 'recommended',
    categoryId: 'starters',
    portionSizes: ['small', 'large'],
    varieties: ['veg'],
    tags: ['starter', 'crispy'],
  },
  {
    id: 'spicy-pappodoms',
    name: 'Spicy Pappodoms',
    description: 'Spicy lentil wafers',
    price: 0.95,
    image: '/images/food/menu/starters-veg/spicy-pappodoms.jpg',
    badge: 'popular',
    categoryId: 'starters',
    portionSizes: ['small', 'large'],
    varieties: ['veg'],
    tags: ['starter', 'spicy'],
  },
  {
    id: 'pickle-tray',
    name: 'Pickle Tray',
    description: 'Set of assorted pickles',
    price: 3.95,
    image: '',
    categoryId: 'starters',
    portionSizes: ['small', 'large'],
    varieties: ['veg'],
    tags: ['sides'],
  },
  {
    id: 'onion-bhaji',
    name: 'Onion Bhaji',
    description: 'Crunchy snack with onions and spices',
    price: 4.5,
    image: '/images/food/menu/starters-veg/onion-bhaji.jpg',
    categoryId: 'starters',
    portionSizes: ['small', 'medium', 'large'],
    varieties: ['veg'],
    tags: ['starter', 'fried'],
  },
  {
    id: 'vegetable-samosa',
    name: 'Vegetable Samosa',
    description: 'Triangle pastry filled with vegetable fillings',
    price: 4.5,
    image: '/images/food/menu/starters-veg/vegetable-samosa.jpg',
    categoryId: 'starters',
    portionSizes: ['small', 'medium', 'large'],
    varieties: ['veg'],
    tags: ['starter', 'pastry', 'samosa'],
  },
  {
    id: 'paneer-tikka',
    name: 'Paneer Tikka',
    description: 'Cottage cheese marinated and cooked in Tandoor',
    price: 5.95,
    image: '/images/food/menu/starters-veg/paneer-tikka.jpg',
    categoryId: 'starters',
    portionSizes: ['half', 'full'],
    varieties: ['paneer'],
    tags: ['starter', 'tikka'],
  },
  {
    id: 'veg-aloo-chat-poori',
    name: 'Veg/Aloo Chat Poori',
    description: 'Deep fried bread with spiced vegetables',
    price: 4.5,
    image: '',
    categoryId: 'starters',
    portionSizes: ['small', 'medium'],
    varieties: ['veg'],
    tags: ['starter', 'chaat'],
  },
  {
    id: 'garlic-mushroom',
    name: 'Garlic Mushroom',
    description: 'Lightly spiced mushroom with garlic',
    price: 4.5,
    image: '',
    categoryId: 'starters',
    portionSizes: ['small', 'medium'],
    varieties: ['veg'],
    tags: ['starter', 'garlic', 'mushroom'],
  },

  // Starters (Non-Veg) — using hero image as placeholder where specific images are unavailable
  {
    id: 'chicken-tikka-tiranga',
    name: 'Chicken Tikka Tiranga',
    description: 'Trio of chicken morsels in distinct flavours',
    price: 5.95,
    image: '',
    categoryId: 'starters-nonveg',
    portionSizes: ['half', 'full'],
    varieties: ['chicken'],
    tags: ['starter', 'tikka'],
  },
  {
    id: 'chicken-tikka',
    name: 'Chicken Tikka',
    description: 'Sliced chicken breast marinated and cooked to perfection',
    price: 5.95,
    image: '/images/food/menu/starters-nonveg/Chicken-tikka.jpg',
    categoryId: 'starters-nonveg',
    portionSizes: ['half', 'full'],
    varieties: ['chicken'],
    tags: ['starter', 'tikka'],
  },
  {
    id: 'meat-samosa',
    name: 'Meat Samosa',
    description: 'Pastry filled with spiced minced meat',
    price: 5.5,
    image: '/images/food/menu/starters-nonveg/meat-samosa.jpg',
    categoryId: 'starters-nonveg',
    portionSizes: ['small', 'medium', 'large'],
    varieties: ['beef', 'lamb'],
    tags: ['starter', 'samosa', 'pastry'],
  },
  {
    id: 'sheesh-kebab',
    name: 'Sheesh Kebab',
    description: 'Ground lamb kebab grilled with spices',
    price: 5.95,
    image: '/images/food/menu/starters-nonveg/sheek-kebab.jpg',
    categoryId: 'starters-nonveg',
    portionSizes: ['half', 'full'],
    varieties: ['lamb'],
    tags: ['starter', 'kebab'],
  },
  {
    id: 'chicken-tikka-chat-poori',
    name: 'Chicken Tikka Chat Poori',
    description: 'Spiced chicken tikka tossed in onion and tomato sauce',
    price: 6.5,
    image: '/images/food/menu/starters-nonveg/chicken-tikka-chat-poori.jpg',
    categoryId: 'starters-nonveg',
    portionSizes: ['small', 'medium'],
    varieties: ['chicken'],
    tags: ['starter', 'chaat'],
  },
  {
    id: 'prawn-poori',
    name: 'Prawn Poori',
    description: 'Prawn tossed in spiced onion and tomato sauce wrapped in poori',
    price: 6.5,
    image: '/images/food/menu/starters-nonveg/prawn-poori.jpg',
    categoryId: 'starters-nonveg',
    portionSizes: ['small', 'medium'],
    varieties: ['prawn'],
    tags: ['starter', 'poori', 'seafood'],
  },
  {
    id: 'king-prawn-chat-poori',
    name: 'King Prawn Chat Poori',
    description: 'King prawn tossed in spiced sauce wrapped and served with salad',
    price: 7.45,
    image: '',
    categoryId: 'starters-nonveg',
    portionSizes: ['small', 'medium'],
    varieties: ['king_prawn'],
    tags: ['starter', 'poori', 'seafood'],
  },
  {
    id: 'mixed-starter',
    name: 'Mixed Starter',
    description: 'Assorted selection of starters and salad',
    price: 7.95,
    image: '/images/food/menu/starters-nonveg/mixed-starter.jpg',
    categoryId: 'starters-nonveg',
    portionSizes: ['small', 'large'],
    varieties: ['chicken', 'lamb', 'veg'],
    tags: ['starter', 'assorted'],
  },
  {
    id: 'soft-shell-crab',
    name: 'Soft Shell Crab',
    description: 'Marinated with garlic, Malabar spices; crispy fried',
    price: 8.2,
    image: '',
    categoryId: 'starters-nonveg',
    portionSizes: ['small', 'medium'],
    varieties: ['fish'],
    tags: ['starter', 'seafood'],
  },

  // Chef's Recommendations
  {
    id: 'homestyle-chicken-curry',
    name: 'Homestyle Chicken Curry (Medium)',
    description: 'Kerala style chicken with coconut milk, curry leaves, ginger and tomatoes',
    price: 11.95,
    image: '',
    categoryId: 'chefs-recommend',
    portionSizes: ['half', 'full'],
    varieties: ['chicken'],
    tags: ['chef', 'kerala', 'medium'],
  },
  {
    id: 'homestyle-vegan-curry',
    name: 'Homestyle Vegan Curry (Medium)',
    description: 'Kerala style fresh vegetables with coconut milk',
    price: 9.95,
    image: '',
    categoryId: 'chefs-recommend',
    portionSizes: ['half', 'full'],
    varieties: ['veg'],
    tags: ['chef', 'kerala', 'medium'],
  },
  {
    id: 'chettinadu-curry',
    name: 'Chettinadu Curry',
    description: 'South Indian dish in rich coconut sauce with onion and tomato',
    price: 11.5,
    image: '',
    categoryId: 'chefs-recommend',
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb', 'beef', 'veg'],
    tags: ['chef', 'south-indian', 'medium'],
  },
  {
    id: 'kadai-curry',
    name: 'Kadai Curry',
    description: 'Indian dish cooked with onions, peppers and crushed spices',
    price: 11.5,
    image: '',
    categoryId: 'chefs-recommend',  
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb', 'beef', 'veg'],
    tags: ['chef', 'medium'],
  },
  {
    id: 'kolhapori-curry',
    name: 'Kolhapori Curry',
    description: 'Flavoursome dish with fresh onion, peppers, spices and grated coconut',
    price: 11.5,
    image: '',
    categoryId: 'chefs-recommend',  
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb', 'beef', 'veg'],
    tags: ['chef', 'medium'],
  },
  {
    id: 'laal-chauk-murg',
    name: 'Laal Chauk Murg (Medium)',
    description: 'Chicken tikka cooked in tomato masala with peppers',
    price: 11.5,
    image: '',
    categoryId: 'chefs-recommend',  
    portionSizes: ['half', 'full'],
    varieties: ['chicken'],
    tags: ['chef', 'medium'],
  },
  {
    id: 'malabar-beef-curry',
    name: 'Malabar Beef Curry (Medium)',
    description: 'Tender beef cooked with shallots and fresh curry leaves',
    price: 11.95,
    image: '',
    categoryId: 'chefs-recommend',  
    portionSizes: ['half', 'full'],
    varieties: ['beef'],
    tags: ['chef', 'malabar', 'medium'],
  },
  {
    id: 'saag-murg',
    name: 'Saag Murg (Medium)',
    description: 'Chicken in medium spiced masala finished with cream and fenugreek',
    price: 11.5,
    image: '',
    categoryId: 'chefs-recommend',  
    portionSizes: ['half', 'full'],
    varieties: ['chicken'],
    tags: ['chef', 'saag', 'medium'],
  },
  {
    id: 'lamb-rogan',
    name: 'Lamb Rogan (Medium)',
    description: 'Aromatic lamb preparation with saffron extract',
    price: 11.95,
    image: '',
    categoryId: 'chefs-recommend',  
    portionSizes: ['half', 'full'],
    varieties: ['lamb'],
    tags: ['chef', 'medium'],
  },
  {
    id: 'saag-gosht',
    name: 'Saag Gosht (Medium)',
    description: 'Succulent lamb cooked in spinach with spices',
    price: 11.95,
    image: '',
    categoryId: 'chefs-recommend',  
    portionSizes: ['half', 'full'],
    varieties: ['lamb'],
    tags: ['chef', 'saag', 'medium'],
  },
  {
    id: 'chutty-curry',
    name: 'Chutty Curry (Very Hot)',
    description: 'Traditional Kerala style chicken curry with a spicy kick',
    price: 11.5,
    image: '',
    categoryId: 'chefs-recommend',  
    portionSizes: ['half', 'full'],
    varieties: ['chicken'],
    tags: ['chef', 'very-hot'],
  },
  {
    id: 'lamb-shank-hyderabadi',
    name: "Lamb Shank Hyderabadi Curry (Medium)",
    description: "Grilled lamb shank cooked with aromatic sauce and chef's spices",
    price: 16.95,
    image: '',
    categoryId: 'chefs-recommend',  
    portionSizes: ['full'],
    varieties: ['lamb'],
    tags: ['chef', 'hyderabadi', 'medium'],
  },

  // Specialities
  {
    id: 'makhani',
    name: 'Makhani (Very Mild)',
    description: 'Butter, mild spices simmered in cream, coconut and masala sauce',
    price: 10.95,
    image: '/images/food/menu/specialities/makhani.jpg',
    categoryId: 'specialities',
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb', 'beef', 'paneer', 'mixed_veg', 'prawn', 'king_prawn'],
    tags: ['speciality', 'very-mild', 'creamy'],
  },
  {
    id: 'passanda',
    name: 'Passanda (Very Mild)',
    description: 'Mildly spiced in green cardamom, rich creamy sauce',
    price: 10.95,
    image: '/images/food/menu/specialities/passanda.jpg',
    categoryId: 'specialities',
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb', 'beef', 'paneer', 'mixed_veg', 'prawn', 'king_prawn'],
    tags: ['speciality', 'very-mild', 'creamy'],
  },
  {
    id: 'ginger-garlic-chilli',
    name: 'Ginger Garlic Chilli',
    description: 'Breast chicken/lamb cooked with chopped ginger, garlic and green chilli',
    price: 11.5,
    image: '',
    categoryId: 'specialities',
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb', 'beef'],
    tags: ['speciality', 'hot', 'garlic'],
  },
  {
    id: 'hari-mirchi-bhuna',
    name: 'Hari Mirchi Bhuna (Fairly Hot)',
    description: 'Tender chicken/lamb with spinach, coriander and chillies',
    price: 11.5,
    image: '',
    categoryId: 'specialities',
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb'],
    tags: ['speciality', 'fairly-hot'],
  },
  {
    id: 'butter-chicken-lamb',
    name: 'Butter Chicken/Lamb (Medium)',
    description: 'Rich butter-based sauce with chef’s spices and herbs',
    price: 10.95,
    image: '/images/food/menu/specialities/butter.jpg',
    categoryId: 'specialities', 
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb'],
    tags: ['speciality', 'medium', 'butter'],
  },
  {
    id: 'captain-patiala',
    name: 'Captain Patiala (Fairly Hot)',
    description: 'Hot tender strips prepared with special herbs, spices and yoghurt',
    price: 11.5,
    image: '',
    categoryId: 'specialities',
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb'],
    tags: ['speciality', 'fairly-hot'],
  },
  {
    id: 'chamili',
    name: 'Chamili (Medium)',
    description: 'Chicken/lamb cooked with onions, pepper and tomato sauce',
    price: 11.5,
    image: '',
    categoryId: 'specialities',
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb'],
    tags: ['speciality', 'medium'],
  },
  {
    id: 'murgi-masala',
    name: 'Murgi Masala (Medium)',
    description: 'Minced lamb with herbs, spices and masala sauce',
    price: 11.5,
    image: '',
    categoryId: 'specialities',
    portionSizes: ['half', 'full'],
    varieties: ['lamb'],
    tags: ['speciality', 'medium'],
  },
  {
    id: 'shatkora',
    name: 'Shatkora (Medium)',
    description: 'Pieces of chicken or meat cooked with citrus shatkora and spices',
    price: 11.5,
    image: '/images/food/menu/specialities/shatkora.jpg',
    categoryId: 'specialities',
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb', 'beef'],
    tags: ['speciality', 'medium'],
  },
  {
    id: 'kali-mirchi-bahar',
    name: 'Kali Mirchi Bahar (Medium to Mild)',
    description: 'Rich yoghurt, cream, garden mint and coriander',
    price: 11.5,
    image: '',
    categoryId: 'specialities',
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb', 'beef'],
    tags: ['speciality', 'medium'],
  },
  {
    id: 'rezala',
    name: 'Rezala (Medium to Mild)',
    description: 'Rich creamy butter sauce with a touch of rose water',
    price: 11.5,
    image: '/images/food/menu/specialities/rezala.jpg',
    categoryId: 'specialities',
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb', 'beef'],
    tags: ['speciality', 'medium'],
  },
  {
    id: 'azuba',
    name: 'Azuba (Medium)',
    description: 'Marinated in spices with peppers, potato and mushrooms',
    price: 11.5,
    image: '',
    categoryId: 'specialities',
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb', 'beef'],
    tags: ['speciality', 'medium'],
  },
  {
    id: 'tawa-chicken',
    name: 'Tawa Chicken (Medium)',
    description: 'Stir fried with medium spices and very thick sauce',
    price: 13.45,
    image: '',
    categoryId: 'specialities',
    portionSizes: ['half', 'full'],
    varieties: ['chicken'],
    tags: ['speciality', 'medium'],
  },
  {
    id: 'garlic-chicken-lamb',
    name: 'Garlic Chicken/Lamb (Medium)',
    description: 'Marinated breast cooked in thick spicy garlic sauce',
    price: 10.95,
    image: '/images/food/menu/specialities/garlic-chilli-chicken.jpg',
    categoryId: 'specialities',
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb'],
    tags: ['speciality', 'medium', 'garlic'],
  },

  // Traditional Curry Dishes
  {
    id: 'tikka-masala',
    name: 'Tikka Masala (Mild)',
    description: 'Velvety onion, yoghurt and spices',
    price: 9.95,
    image: '/images/food/menu/traditional-curry-dishes/tikka-masala.jpg',
    categoryId: 'traditional-curry',
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb', 'beef', 'paneer', 'mixed_veg', 'prawn', 'king_prawn'],
    tags: ['traditional', 'mild'],
  },
  {
    id: 'korma',
    name: 'Korma (Mild)',
    description: 'Rich creamy coconut sauce with nutmeg and coriander',
    price: 9.95,
    image: '/images/food/menu/traditional-curry-dishes/korma.jpg',
    categoryId: 'traditional-curry',
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb', 'beef', 'paneer', 'mixed_veg', 'prawn', 'king_prawn'],
    tags: ['traditional', 'mild', 'creamy'],
  },
  {
    id: 'pathia',
    name: 'Pathia (Sweet Sour and Hot)',
    description: 'Persian dish with sweet, hot and sour spices',
    price: 9.95,
    image: '/images/food/menu/traditional-curry-dishes/pathia.jpg',
    categoryId: 'traditional-curry',
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb', 'beef', 'paneer', 'mixed_veg', 'prawn', 'king_prawn'],
    tags: ['traditional', 'sweet-sour', 'hot'],
  },
  {
    id: 'bhuna',
    name: 'Bhuna (Medium)',
    description: 'Well spiced with thick gravy',
    price: 9.95,
    image: '/images/food/menu/traditional-curry-dishes/bhuna.jpg',
    categoryId: 'traditional-curry',
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb', 'beef', 'paneer', 'mixed_veg', 'prawn', 'king_prawn'],
    tags: ['traditional', 'medium'],
  },
  {
    id: 'balti',
    name: 'Balti (Medium)',
    description: 'Punjabi dish with onion, tomato, fenugreek and coriander',
    price: 9.95,
    image: '/images/food/menu/traditional-curry-dishes/balti.jpg',
    categoryId: 'traditional-curry',
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb', 'beef', 'paneer', 'mixed_veg', 'prawn', 'king_prawn'],
    tags: ['traditional', 'medium'],
  },
  {
    id: 'dupiaza',
    name: 'Dupiaza (Medium)',
    description: 'Onion and tomato base with chef’s special spices',
    price: 9.95,
    image: '/images/food/menu/traditional-curry-dishes/chicken-dopiaza.jpg',
    categoryId: 'traditional-curry',
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb', 'beef', 'paneer', 'mixed_veg', 'prawn', 'king_prawn'],
    tags: ['traditional', 'medium'],
  },
  {
    id: 'korai',
    name: 'Korai (Medium)',
    description: 'Stir fried with medium spices and chef’s special sauce',
    price: 9.95,
    image: '/images/food/menu/traditional-curry-dishes/Korai.jpg',
    categoryId: 'traditional-curry',
    portionSizes: ['half', 'full'],
    varieties: ['chicken', 'lamb', 'beef', 'paneer', 'mixed_veg', 'prawn', 'king_prawn'],
    tags: ['traditional', 'medium'],
  },
  {
    id: "kashmiri-curry",
    name: "Kashmiri (Very Mild)",
    description: "Cooked with spices and sweet fresh fruits",
    price: null,
    image: "",
    categoryId: "traditional-curry",
    portionSizes: [],
    varieties: ["veg", "non-veg"],
    tags: ["mild", "curry"]
  },
  {
    id: "madras-curry",
    name: "Madras (Hot)",
    description: "Curry and madras infused with different spicy flavours",
    price: null,
    image: "/images/food/menu/traditional-curry-dishes/madras.jpg",
    categoryId: "traditional-curry",
    portionSizes: [],
    varieties: ["non-veg"],
    tags: ["hot", "curry"]
  },
  {
    id: "vindaloo-curry",
    name: "Vindaloo (Very Hot)",
    description: "Cooked with hot spice and sauce",
    price: null,
    image: "/images/food/menu/traditional-curry-dishes/vindaloo.jpg",
    categoryId: "traditional-curry",
    portionSizes: [],
    varieties: ["non-veg"],
    tags: ["very-hot", "curry"]
  },
  {
    id: "jalfrezi-curry",
    name: "Jalfrezi (Hot)",
    description: "Delightfully flavorful curry with chicken in a spicy tomato sauce with peppers and onions",
    price: null,
    image: "/images/food/menu/traditional-curry-dishes/chicken-jalfrezi.jpg",
    categoryId: "traditional-curry",
    portionSizes: [],
    varieties: ["non-veg"],
    tags: ["hot", "curry"]
  },
  {
    id: "ceylon-curry",
    name: "Ceylon (Hot)",
    description: "Cooked with coconut lemon juice and chilli resulting in an exotic sweet and sour combination",
    price: null,
    image: "/images/food/menu/traditional-curry-dishes/ceylon.jpg",
    categoryId: "traditional-curry",
    portionSizes: [],
    varieties: ["non-veg"],
    tags: ["hot", "curry", "coconut"]
  },
  {
    id: "lahore-balti",
    name: "Lahore Balti (Medium)",
    description: "Prepared with chicken, lamb, prawn, mushroom, spinach and chef’s special exotic Balti sauce",
    price: 11.95,
    image: "/images/food/menu/traditional-curry-dishes/lahore-balti.jpg",
    categoryId: "traditional-curry",
    portionSizes: [],
    varieties: ["non-veg"],
    tags: ["medium", "balti"]
  },
  {
    id: "malayan-curry",
    name: "Malayan (Mild)",
    description: "Cooked with spices, sweet fruits, pineapple and fresh cream",
    price: null,
    image: "/images/food/menu/traditional-curry-dishes/malaya.jpg",
    categoryId: "traditional-curry",
    portionSizes: [],
    varieties: ["non-veg"],
    tags: ["mild", "curry", "fruity"]
  },

  // ===== Seafood =====
  {
    id: "aleppey-curry-prawn",
    name: "Alleppey Curry (Prawn)",
    description: "Prawn simmered with ginger, raw mango and coconut gravy tempered with fenu-greek and curry leaves",
    price: 11.95,
    image: "",
    categoryId: "seafood",
    portionSizes: [],
    varieties: ["seafood"],
    tags: ["medium", "prawn", "curry"]
  },
  {
    id: "aleppey-curry-kingprawn-salmon",
    name: "Alleppey Curry (King Prawn/Salmon)",
    description: "Choice of King Prawn or Salmon in ginger, raw mango and coconut gravy tempered with fenu-greek and curry leaves",
    price: 15.95,
    image: "",
    categoryId: "seafood",
    portionSizes: [],
    varieties: ["seafood"],
    tags: ["medium", "seafood", "curry"]
  },

  // ===== From the Clay Oven =====
  {
    id: "chicken-tikka-tiranga",
    name: "Chicken Tikka Tiranga",
    description: "Trio of chicken morsel in three distinct flavour of basil, star anise and Kashmiri chilli cooked to perfection in Tandoor",
    price: 9.95,
    image: "",
    categoryId: "from-the-clay-oven",
    portionSizes: [],
    varieties: ["chicken"],
    tags: ["medium-hot", "tandoor"]
  },
  {
    id: "chicken-tikka",
    name: "Chicken Tikka",
    description: "Sliced chicken breast marinated in yogurt and spices cooked to perfection in Tandoor",
    price: 9.75,
    image: "/images/food/menu/from-the-clay-oven/chicken-tikka.jpg",
    badge: "popular",
    categoryId: "from-the-clay-oven",
    portionSizes: [],
    varieties: ["chicken"],
    tags: ["tandoor"]
  },
  {
    id: "tandoori-chicken",
    name: "Tandoori Chicken",
    description: "Baby chicken marinated in Kashmiri chilli, spices, fenugreek leaves, yogurt and mustard oil cooked to perfection in Tandoor",
    price: 9.95,
    image: "/images/food/menu/from-the-clay-oven/tandoori-chicken.jpg",
    categoryId: "from-the-clay-oven",
    portionSizes: ["half", "full"],
    varieties: ["chicken"],
    tags: ["tandoor"]
  },
  {
    id: "chicken-shashlick",
    name: "Chicken Shashlick",
    description: "Chicken breast marinated in turmeric, yogurt and chilli with diced onion, tomato and bell pepper. Cooked in Tandoor",
    price: 14.5,
    image: "/images/food/menu/from-the-clay-oven/chicken-shashlick.jpg",
    categoryId: "from-the-clay-oven",
    portionSizes: [],
    varieties: ["chicken"],
    tags: ["tandoor", "shashlick"]
  },
  {
    id: "lamb-shashlick",
    name: "Lamb Shashlick",
    description: "Tender pieces of lamb marinated in turmeric, yogurt and chilli with diced onion, tomato and bell pepper. Cooked in Tandoor",
    price: 15.15,
    image: "",
    categoryId: "from-the-clay-oven",
    portionSizes: [],
    varieties: ["lamb"],
    tags: ["tandoor", "shashlick"]
  },
  {
    id: "kingprawn-shashlick",
    name: "King Prawn Shashlick",
    description: "King prawn marinated in turmeric, yogurt and chilli with diced onion, tomato and bell pepper. Cooked in Tandoor",
    price: 15.95,
    image: "/images/food/menu/from-the-clay-oven/tandoori-prawns.jpg",
    categoryId: "from-the-clay-oven",
    portionSizes: [],
    varieties: ["seafood"],
    tags: ["tandoor", "shashlick"]
  },
  {
    id: "paneer-shashlick",
    name: "Paneer Shashlick",
    description: "Cottage cheese marinated in turmeric, yogurt and chilli with diced onion, tomato and bell pepper. Cooked in Tandoor",
    price: 14.5,
    image: "/images/food/menu/from-the-clay-oven/Paneer-Tikka.jpg",
    categoryId: "from-the-clay-oven",
    portionSizes: [],
    varieties: ["veg"],
    tags: ["tandoor", "shashlick"]
  },
  {
    id: "dill-salmon",
    name: "Dill Salmon",
    description: "Salmon cubes marinated with dill leaves, ginger, garlic, mustard paste, honey, corn seeds and yogurt. Finished in Tandoor",
    price: 16.95,
    image: "/images/food/menu/from-the-clay-oven/salmon-tikka.jpg",
    categoryId: "from-the-clay-oven",
    portionSizes: [],
    varieties: ["seafood"],
    tags: ["tandoor", "salmon"]
  },
  {
    id: "hyderabadi-lamb-shank",
    name: "Hyderabadi Lamb Shank",
    description: "Lamb shank marinated with aromatic Hyderabadi spices, slow cooked in pot and roasted in Tandoor served with mustard tempered potato mash and salad",
    price: 16.95,
    image: "",
    categoryId: "from-the-clay-oven",
    portionSizes: [],
    varieties: ["lamb"],
    tags: ["tandoor", "hyderabadi"]
  },
  {
    id: "laal-jinga-tandoori",
    name: "Laal Jinga Tandoori",
    description: "King prawns marinated with mustard paste, Kashmiri chilli, carom seeds, aromatic garam masala yogurt and roasted in Tandoor",
    price: 17.95,
    image: "",
    categoryId: "from-the-clay-oven",
    portionSizes: [],
    varieties: ["seafood"],
    tags: ["tandoor", "prawn"]
  },
  {
    id: "tandoori-mix-grill",
    name: "Tandoori Mix Grill",
    description: "Chicken tikka, sheek kebab, tandoori chicken, king prawn and salmon tikka cooked to perfection and served with chutney and salad",
    price: 17.95,
    image: "",
    badge: "recommended",
    categoryId: "from-the-clay-oven",
    portionSizes: [],
    varieties: ["mixed_veg"],
    tags: ["tandoor", "grill"]
  },

  // ===== Malabar Biryani =====
  {
    id: "veg-biryani",
    name: "Vegetable Biryani",
    description: "Classic DUM biryani preparation from Malabar coast with chef’s special spices. Served with biryani sauce",
    price: 11.5,
    image: "",
    categoryId: "malabar-biriyani",
    portionSizes: [],
    varieties: ["veg"],
    tags: ["biryani"]
  },
  {
    id: "chicken-biryani",
    name: "Chicken/Prawns Biryani",
    description: "Classic DUM biryani preparation with chicken or prawns and chef’s special spices. Served with biryani sauce",
    price: 13.95,
    image: "/images/food/menu/malabar-biryani/chicken-tk-biryani.jpg",
    categoryId: "malabar-biriyani",
    portionSizes: [],
    varieties: ["chicken", "seafood"],
    tags: ["biryani"]
  },
  {
    id: "lamb-biryani",
    name: "Lamb Biryani",
    description: "Classic DUM biryani preparation with lamb and chef’s special spices. Served with biryani sauce",
    price: 14.45,
    image: "/images/food/menu/malabar-biryani/lamb-biryani.jpg",
    categoryId: "malabar-biriyani",
    portionSizes: [],
    varieties: ["lamb"],
    tags: ["biryani"]
  },
  {
    id: "kingprawn-biryani",
    name: "King Prawn Biryani",
    description: "Classic DUM biryani preparation with king prawn and chef’s special spices. Served with biryani sauce",
    price: 16.5,
    image: "",
    categoryId: "malabar-biriyani",
    portionSizes: [],
    varieties: ["seafood"],
    tags: ["biryani"]
  },
  {
    id: "special-biryani",
    name: "Special Biryani",
    description: "Classic DUM biryani with chef’s choice of mixed meat or seafood",
    price: 16.95,
    image: "/images/food/menu/malabar-biryani/special-biryani.jpg",
    badge: "recommended",
    categoryId: "malabar-biriyani",
    portionSizes: [],
    varieties: ["mixed_veg"],
    tags: ["biryani", "special"]
  },

  // ===== Vegetarian =====
  {
    id: "aloo-gobi-masala",
    name: "Aloo Gobi Masala",
    description: "Pan finished baby potatoes and cauliflower florets with onions, ginger, tomatoes, coriander and spices",
    price: 8.95,
    image: "/images/food/menu/vegetarian/aloo-gobi-masala.jpg",
    categoryId: "vegetarian",
    portionSizes: [],
    varieties: ["veg"],
    tags: ["veg", "curry"]
  },
  {
    id: "bombai-aloo",
    name: "Bombai Aloo",
    description: "Dry preparation of baby potatoes with cumin, onions, ginger and tomatoes",
    price: 8.95,
    image: "/images/food/menu/vegetarian/bombay-aloo.jpg",
    categoryId: "vegetarian",
    portionSizes: [],
    varieties: ["veg"],
    tags: ["veg", "dry"]
  },
  {
    id: "saag-aloo",
    name: "Saag Aloo",
    description: "A classic potato and spinach dish with spices, onion tomato masala and cream",
    price: 8.95,
    image: "/images/food/menu/vegetarian/saag-aloo.jpg",  
    categoryId: "vegetarian",
    portionSizes: [],
    varieties: ["veg"],
    tags: ["veg", "spinach"]
  },
  {
    id: "saag-paneer",
    name: "Saag Paneer",
    description: "Cottage cheese slow cooked with onions, tomatoes and spinach with aromatic spices and cream",
    price: 8.95,
    image: "/images/food/menu/vegetarian/saag-paneer.jpg",
    categoryId: "vegetarian",
    portionSizes: [],
    varieties: ["veg"],
    tags: ["paneer", "spinach", "curry"]
  },
  {
    id: "tadka-daal",
    name: "Tadka Daal",
    description: "Home style tempered masoor and moong dal with cumin, garlic, onions and turmeric",
    price: 8.95,
    image: "/images/food/menu/vegetarian/tarka-dal.jpg",
    categoryId: "vegetarian",
    portionSizes: [],
    varieties: ["veg"],
    tags: ["dal", "veg"]
  },
  {
    id: "chana-masala",
    name: "Chana Masala",
    description: "Chickpeas cooked Punjabi style with cumin, onions, ginger, Kashmiri chilli, coriander and dry mango powder",
    price: 8.95,
    image: "/images/food/menu/vegetarian/chana-bhaji.jpg",
    categoryId: "vegetarian",
    portionSizes: [],
    varieties: ["veg"],
    tags: ["chickpeas", "veg"]
  },
  {
    id: "bhindi-bhaji",
    name: "Bhindi Bhaji",
    description: "Deep fried Okra tossed in onion tomato masala with kasuri methi, coriander and seasoned with chaat masala",
    price: 8.95,
    image: "/images/food/menu/vegetarian/bhindi-bhaji.jpg",
    categoryId: "vegetarian",
    portionSizes: [],
    varieties: ["veg"],
    tags: ["okra", "veg"]
  },
  {
    id: "mutter-paneer",
    name: "Mutter Paneer",
    description: "Homemade cottage cheese and green peas stir fried with herbs and spices",
    price: 8.95,
    image: "/images/food/menu/vegetarian/muttar-paneer.jpg",
    categoryId: "vegetarian",
    portionSizes: [],
    varieties: ["veg"],
    tags: ["paneer", "peas", "veg"]
  },
  {
    "id": "brinjol-bhaji",
    "name": "Brinjol Bhaji (Aubergine)",
    "description": "A rich, simple aubergine dish that packs an amazing punch in terms of flavour",
    "price": null,
    "image": "/images/food/menu/vegetarian/brinjal-bhaji.jpg",
    "categoryId": "vegetarian",
    "portionSizes": [],
    "varieties": ["veg"],
    "tags": ["veg", "side"]
  },
  {
    "id": "saag-bhaji",
    "name": "Saag Bhaji (Spinach)",
    "description": "Very tasty variation on spinach",
    "price": null,
    "image": "/images/food/menu/vegetarian/saag-bhaji.jpg",
    "categoryId": "vegetarian",
    "portionSizes": [],
    "varieties": ["veg"],
    "tags": ["veg", "side"]
  },
  {
    "id": "mushroom-bhaji",
    "name": "Mushroom Bhaji",
    "description": "Fresh mushrooms tossed with onion and with a touch of chefs own spices",
    "price": null,
    "image": "/images/food/menu/vegetarian/mushroom-bhaji.jpg",
    "categoryId": "vegetarian",
    "portionSizes": [],
    "varieties": ["veg"],
    "tags": ["veg", "side"]
  },
  // ===== Rice Dishes =====
  {
    "id": "plain-basmati-rice",
    "name": "Plain/Basmati Rice",
    "description": "Simple boiled rice.",
    "price": 3.95,
    "image": "/images/food/menu/rice/rice-plain-boiled-basmati.jpg",
    "categoryId": "rice",
    "portionSizes": [],
    "varieties": ["veg"],
    "tags": ["rice", "veg"]
  },
  {
    "id": "pilav-rice",
    "name": "Pilav Rice",
    "description": "Rice cooked in a seasoned broth.",
    "price": 4.50,
    "image": "/images/food/menu/rice/rice-pilau.jpg",
    "categoryId": "rice",
    "portionSizes": [],
    "varieties": [],
    "tags": ["rice"]
  },
  {
    "id": "mushroom-rice",
    "name": "Mushroom Rice",
    "description": "Rice mixed with fresh mushrooms.",
    "price": 4.95,
    "image": "/images/food/menu/rice/mushroom-rice.jpg",
    "categoryId": "rice",
    "portionSizes": [],
    "varieties": [],
    "tags": ["rice"]
  },
  {
    "id": "coconut-rice",
    "name": "Coconut Rice",
    "description": "Rice infused with coconut flavour.",
    "price": 4.95,
    "image": "/images/food/menu/rice/coconut-rice.jpg",
    "categoryId": "rice",
    "portionSizes": [],
    "varieties": [],
    "tags": ["rice"]
  },
  {
    "id": "garlic-rice",
    "name": "Garlic Rice",
    "description": "Rice cooked with garlic.",
    "price": 4.95,
    "image": "/images/food/menu/rice/garlic-rice.jpg",
    "categoryId": "rice",
    "portionSizes": [],
    "varieties": [],
    "tags": ["rice"]
  },
  {
    "id": "lemon-onion-rice",
    "name": "Lemon & Onion Rice",
    "description": "Rice mixed with lemon and onion.",
    "price": 4.95,
    "image": "/images/food/menu/rice/lemon-rice.jpg",
    "categoryId": "rice",
    "portionSizes": [],
    "varieties": [],
    "tags": ["rice"]
  },
  {
    "id": "egg-rice",
    "name": "Egg Rice",
    "description": "Rice cooked with egg.",
    "price": 4.95,
    "image": "/images/food/menu/rice/egg-rice.jpg",
    "categoryId": "rice",
    "portionSizes": [],
    "varieties": [],
    "tags": ["rice"]
  },
  {
    "id": "kheema-rice",
    "name": "Kheema Rice",
    "description": "Rice mixed with spiced minced meat.",
    "price": 4.95,
    "image": "/images/food/menu/rice/keema-rice.jpg",
    "categoryId": "rice",
    "portionSizes": [],
    "varieties": [],
    "tags": ["rice", "meat"]
  },
  {
    "id": "chefs-special-rice",
    "name": "Chef's Special Rice",
    "description": "A mix of ingredients chosen by the chef.",
    "price": 4.95,
    "image": "",
    "categoryId": "rice",
    "portionSizes": [],
    "varieties": [],
    "tags": ["rice", "special"]
  },
  {
    "id": "half-pilav-rice-chips",
    "name": "Half Pilav Rice & Half Chips",
    "description": "A combination of pilav rice and chips.",
    "price": 5.50,
    "image": "/images/food/menu/rice/half-rice-half-chips.jpg",
    "categoryId": "rice",
    "portionSizes": [],
    "varieties": [],
    "tags": ["rice", "chips"]
  },

  // --- Breads ---
  {
    "id": "tandoori-roti",
    "name": "Tandoori Roti",
    "description": "Unleavened whole wheat flat bread baked in Tandoor",
    "price": 3.50,
    "image": "/images/food/menu/bread/tandoori-roti.jpg",
    "categoryId": "bread",
    "portionSizes": [],
    "varieties": ["veg"],
    "tags": ["bread", "veg"]
  },
  {
    "id": "plain-nan",
    "name": "Plain Nan",
    "description": "Leavened flat bread made from refined flour, baked in Tandoor",
    "price": 3.50,
    "image": "/images/food/menu/bread/plain-naan.jpg",
    "categoryId": "bread",
    "portionSizes": [],
    "varieties": [],
    "tags": ["bread"]
  },
  {
    "id": "peshwari-nan",
    "name": "Peshwari Nan",
    "description": "Mango and coconut stuffed leavened flat refined bread, baked in Tandoor",
    "price": 3.95,
    "image": "/images/food/menu/bread/peshwari-naan.jpg",
    "categoryId": "bread",
    "portionSizes": [],
    "varieties": ["sweet", "veg"],
    "tags": ["bread"]
  },
  {
    "id": "kheema-nan",
    "name": "Kheema Nan",
    "description": "Nan stuffed with spiced minced meat",
    "price": 3.95,
    "image": "/images/food/menu/bread/keema-aan.jpg",
    "categoryId": "bread",
    "portionSizes": [],
    "varieties": ["meat"],
    "tags": ["bread", "meat"]
  },
  {
    "id": "garlic-nan",
    "name": "Garlic Nan",
    "description": "Nan topped with garlic and coriander",
    "price": 3.95,
    "image": "/images/food/menu/bread/garlic-naan.jpg",
    "categoryId": "bread",
    "portionSizes": [],
    "varieties": ["veg"],
    "tags": ["bread", "veg"]
  },
  {
    "id": "chilli-nan",
    "name": "Chilli Nan",
    "description": "Nan topped with crushed chilli baked in tandoor and finished off with butter.",
    "price": 3.95,
    "image": "/images/food/menu/bread/chilli-naan.jpg",
    "categoryId": "bread",
    "portionSizes": [],
    "varieties": ["spicy"],
    "tags": ["bread", "spicy"]
  },
  {
    "id": "malabar-poratta",
    "name": "Malabar Poratta",
    "description": "A layered flatbread made from refined flour",
    "price": 2.95,
    "image": "/images/food/menu/bread/malabar(aloo paratha).jpg",
    "categoryId": "bread",
    "portionSizes": [],
    "varieties": ["veg"],
    "tags": ["bread", "veg"]
  },
  {
    "id": "chapati",
    "name": "Chapati",
    "description": "A round flat unleavened bread that made of whole-wheat flour and cooked on a griddle.",
    "price": 2.45,
    "image": "/images/food/menu/bread/Chapatti.jpg",
    "categoryId": "bread",
    "portionSizes": [],
    "varieties": ["veg"],
    "tags": ["bread", "veg"]
  },
  {
    "id": "cheese-nan",
    "name": "Cheese Nan",
    "description": "Nan stuffed with cheese.",
    "price": 3.95,
    "image": "/images/food/menu/bread/cheese-naan.jpg",
    "categoryId": "bread",
    "portionSizes": [],
    "varieties": [],
    "tags": ["bread", "cheese"]
  },

  // --- Extras ---
  {
    "id": "any-curry-sauce",
    "name": "Any Curry Sauce",
    "description": "A side serving of any curry sauce from the menu.",
    "price": 4.95,
    "image": "/images/food/menu/extras/any-curry-sause.jpg",
    "categoryId": "extras",
    "portionSizes": [],
    "varieties": [],
    "tags": ["sauce", "extra"]
  },
  {
    "id": "plain-chips",
    "name": "Plain Chips",
    "description": "Classic deep-fried potato chips.",
    "price": 3.95,
    "image": "/images/food/menu/extras/chips.jpg",
    "categoryId": "extras",
    "portionSizes": [],
    "varieties": ["veg"],
    "tags": ["chips", "extra", "veg"]
  },
  {
    "id": "masala-chips",
    "name": "Masala Chips",
    "description": "Chips tossed in Indian spices.",
    "price": 4.25,
    "image": "/images/food/menu/extras/chips-masala.jpg",
    "categoryId": "extras",
    "portionSizes": [],
    "varieties": ["spicy", "veg"],
    "tags": ["chips", "extra", "veg"]
  },
  {
    "id": "mango-chutney",
    "name": "Mango Chutney",
    "description": "Sweet and tangy mango relish.",
    "price": 0.95,
    "image": "/images/food/menu/extras/mango-chutney.jpg",
    "categoryId": "extras",
    "portionSizes": [],
    "varieties": ["veg", "sweet"],
    "tags": ["chutney", "extra", "veg"]
  },
  {
    "id": "mint-sauce",
    "name": "Mint Sauce",
    "description": "Cool and refreshing mint dipping sauce.",
    "price": 0.95,
    "image": "/images/food/menu/extras/mint-sauce.jpg",
    "categoryId": "extras",
    "portionSizes": [],
    "varieties": ["veg"],
    "tags": ["sauce", "extra", "veg"]
  },
  {
    "id": "onion-salad",
    "name": "Onion Salad",
    "description": "Sliced onions in a light dressing.",
    "price": 0.95,
    "image": "/images/food/menu/extras/onion-salad&popadoms.jpg",
    "categoryId": "extras",
    "portionSizes": [],
    "varieties": ["veg"],
    "tags": ["salad", "extra", "veg"]
  },
  {
    "id": "lemon-pickle",
    "name": "Lemon Pickle",
    "description": "Tangy and spicy lemon preserve.",
    "price": 0.95,
    "image": "",
    "categoryId": "extras",
    "portionSizes": [],
    "varieties": ["spicy", "veg"],
    "tags": ["pickle", "extra", "veg"]
  },

  // --- Kids Meal ---
  {
    "id": "kids-5pcs-chicken-nuggets-chips",
    "name": "5PCS Chicken Nuggets and Chips",
    "description": "Five pieces of chicken nuggets served with chips.",
    "price": 7.45,
    "image": "/images/food/menu/kids-meaal/nuggets-and-chips.jpg",
    "categoryId": "kids-meal",
    "portionSizes": [],
    "varieties": ["kids"],
    "tags": ["kids", "chicken", "chips"]
  },
  {
    "id": "kids-chicken-korma-chips",
    "name": "Chicken Korma and Chips",
    "description": "Mild chicken korma served with chips.",
    "price": 8.00,
    "image": "",
    "categoryId": "kids-meal",
    "portionSizes": [],
    "varieties": ["kids", "mild"],
    "tags": ["kids", "chicken", "chips", "curry"]
  },
  {
    "id": "kids-chicken-tikka-masala-chips",
    "name": "Chicken Tikka Masala and Chips",
    "description": "Chicken tikka masala served with chips.",
    "price": 8.00,
    "image": "",
    "categoryId": "kids-meal",
    "portionSizes": [],
    "varieties": ["kids"],
    "tags": ["kids", "chicken", "chips", "curry"]
  },
  {
    "id": "kids-chicken-tikka-masala-chips-rice",
    "name": "Chicken Tikka Masala, Chips & Rice",
    "description": "Chicken tikka masala served with a combination of chips and rice.",
    "price": 9.50,
    "image": "",
    "categoryId": "kids-meal",
    "portionSizes": [],
    "varieties": ["kids"],
    "tags": ["kids", "chicken", "chips", "rice", "curry"]
  }
];

// Helpers to work with the category tree and product counts
export function findCategoryById(id: string, nodes: MenuCategory[] = categories): MenuCategory | undefined {
  for (const node of nodes) {
    if (node.id === id) return node;
    const found = findCategoryById(id, node.children);
    if (found) return found;
  }
  return undefined;
}

export function collectDescendantIds(id: string, nodes: MenuCategory[] = categories): string[] {
  const start = findCategoryById(id, nodes);
  if (!start) return [];
  const acc: string[] = [];
  const walk = (n: MenuCategory) => {
    for (const child of n.children) {
      acc.push(child.id);
      walk(child);
    }
  };
  walk(start);
  return acc;
}

export function countProductsInTree(rootId: string): number {
  const ids = new Set([rootId, ...collectDescendantIds(rootId)]);
  return products.filter((p) => ids.has(p.categoryId)).length;
}